### PR TITLE
frontend: sort logs in build detail

### PR DESCRIPTION
**Pull request by xsuchy**
so they are in the same order and do not confuse users
addressing: https://social.linux.pizza/@knurd42/109702895855625653

### CODE REVIEW

**Review by FrostyX — APPROVED** [review]
+1

**Review by praiskup — APPROVED** [review]
We want to sort like this `[builder-live.log, backend.log, import.log]` (from the most frequently observed file to least).  We are just lucky `sort()` helps :-).

**Review by praiskup — COMMENTED** [review]
Ok, taking back.  It doesn't sort this way.  Would you mind replacing `sort()` with something that sorts this way?

**Comment by praiskup** [comment]
That sounds good!

**Pull request closed without merging**
