### PR TITLE
Fix tracebacks from OIDC

### PR DESCRIPTION
**Pull request by FrostyX**
The `oidc.py` has logging statements in case some configuration
options are missing. They traceback with this weird traceback because
they don't use our configured logger from `app`.

    Message: 'OIDC_LOGIN or OIDC_PROVIDER_NAME is empty'
    Arguments: ()
    ERROR:coprs.oidc:OIDC_LOGIN or OIDC_PROVIDER_NAME is empty
    --- Logging error ---
    Traceback (most recent call last):
      File "/usr/lib64/python3.11/logging/__init__.py", line 449, in format
        return self._format(record)
               ^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.11/logging/__init__.py", line 445, in _format
        return self._fmt % values
               ~~~~~~~~~~^~~~~~~~
    KeyError: 'user'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    ...

### CODE REVIEW

**Comment by FrostyX** [comment]
I can't properly test it since we don't use OIDC. Can you please take a look @pkking if it doesn't break your instance?

**Comment by pkking** [comment]
> I can't properly test it since we don't use OIDC. Can you please take a look @pkking if it doesn't break your instance?

Thanks @FrostyX , i will test it in our instance and reply ASAP

**Comment by pkking** [comment]
@FrostyX Hi, Jakub, just test it and got exception:
```
copr-frontend-httpd User: None
copr-frontend-httpd Traceback (most recent call last):
copr-frontend-httpd   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
copr-frontend-httpd     rv = self.dispatch_request()
copr-frontend-httpd   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
copr-frontend-httpd     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
copr-frontend-httpd   File "/usr/share/copr/coprs_frontend/coprs/views/misc.py", line 102, in oidc_login
copr-frontend-httpd     return oidc.copr.authorize_redirect(redirect_uri)
copr-frontend-httpd AttributeError: module 'coprs.oidc' has no attribute 'copr' 
```
I think maybe it was caused by some cyclic deps, `view/misc.py` depends on `coprs.oidc`, but in `coprs/__init__.py` oidc was initialized after misc imports, i tried moved the 
```
import os                                                                                                                                                                                                                                
import flask                                                                                                                                                                                                                             
                                                                                                                                                                                                                                         
...
# some config initialized code                                                                                                                                                                                   
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True       

# move the initialized code here
from coprs.log import setup_log                                                                                                                                                                                                          
import coprs.context_processors                                                                                                                                                                                                          
                                                                                                                                                                                                                                         
with app.app_context():                                                                                                                                                                                                                  
    setup_log()                                                                                                                                                                                                                          
                                                                                                                                                                                                                                         
from coprs.oidc import init_oidc_app                                                                                                                                                                                                     
oidc = init_oidc_app(app)    
```
just right before `init_oidc_app(app)` and it works

**Comment by pkking** [comment]
> Thank you for the test and further debugging @pkking,
> 
> > I think maybe it was caused by some cyclic deps, view/misc.py depends on coprs.oidc, but in coprs/**init**.py oidc was initialized after misc imports, i tried moved the setup_log() just right before init_oidc_app(app) instead of moving the init_oidc_app(app) to middle of the **init**.py file and it works
> 
> I updated the PR accordingly. Hopefully, it should work now?

Sorry for the delay, will test and feedback today :)

**Comment by pkking** [comment]
> > Thank you for the test and further debugging @pkking,
> > > I think maybe it was caused by some cyclic deps, view/misc.py depends on coprs.oidc, but in coprs/**init**.py oidc was initialized after misc imports, i tried moved the setup_log() just right before init_oidc_app(app) instead of moving the init_oidc_app(app) to middle of the **init**.py file and it works
> > 
> > 
> > I updated the PR accordingly. Hopefully, it should work now?
> 
> Sorry for the delay, will test and feedback today :)

Applied the patch and it works 💯, thanks

**Review by praiskup — APPROVED** [review]

**Pull request merged**
