### PR TITLE
Fix backend tests

### PR DESCRIPTION
**Pull request by FrostyX**
Some of the backend tests were broken after merging PR #2920

### CODE REVIEW

**Comment by FrostyX** [comment]
To fix the one remaining test, we could either merge https://github.com/fedora-copr/test-data-copr-backend/pull/3 or we can remove the assert

```
>           assert level <= logging.INFO
E           assert 30 <= 20
E            +  where 20 = logging.INFO
```

**Comment by praiskup** [comment]
The test PR merged.

**Comment by FrostyX** [comment]
Updated, the tests pass now.

**Comment by praiskup** [comment]
Does it make sense to have those commits separated?  Seems like they are closely related to each other.

**Comment by FrostyX** [comment]
Squashed

**Pull request merged**
