### PR TITLE
Explicitly depend on SQLAlchemy < 2

### PR DESCRIPTION
**Pull request by nphilipp**

### CODE REVIEW

**Comment by FrostyX** [comment]
Hello @nphilipp,
thank you for the PR.

I recently worked on compatibility with SQLAlchemy 2, please take a look at #3172. I think we don't have to stay on 1.x anymore?

**Comment by nphilipp** [comment]
Fedora 40 has SQLAlchemy 2.0.x, prior versions have 1.4.x which comes with the new API. Let me take a look at that other PR!

**Comment by nphilipp** [comment]
@FrostyX yeah, with that patch in, restricting to sqlalchemy versions < 2 isn’t necessary.

**Comment by FrostyX** [comment]
Alright, thank you for taking a look :-)

**Pull request closed without merging**
