### PR TITLE
docker-compose obsolete

### PR DESCRIPTION
**Pull request by andykimpe**
docker required build and admin mode execute

if not execute docker build return error

```
WARNING: Image for service keygen-httpd was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating copr_database_1 ... 
Creating copr_keygen-signd_1 ... 
Creating copr_distgit_1      ... 
Creating copr_keygen-httpd_1 ... 
Creating copr_distgit-httpd_1 ... error
Creating copr_redis_1         ... 
Creating copr_builder_1       ... 

Creating copr_keygen-httpd_1  ... error
Creating copr_database_1      ... done
Creating copr_keygen-signd_1  ... done
Creating copr_distgit_1       ... done

ERROR: for copr_keygen-httpd_1  Cannot create container for service keygen-httpdCreating copr_redis_1         ... done
Creating copr_builder_1       ... done
Creating copr_resalloc_1      ... done
Creating copr_backend-log_1   ... done
Creating copr_backend-action_1 ... done
Creating copr_backend_httpd_1  ... done
Creating copr_backend-build_1  ... done

ERROR: for distgit-httpd  Cannot create container for service distgit-httpd: failed to mkdir /var/lib/docker/volumes/copr_dist-git/_data/cache/lookaside/pkgs: mkdir /var/lib/docker/volumes/copr_dist-git/_data/cache/lookaside/pkgs: file exists

ERROR: for keygen-httpd  Cannot create container for service keygen-httpd: failed to mkdir /var/lib/docker/volumes/copr_copr-keygen/_data/phrases: mkdir /var/lib/docker/volumes/copr_copr-keygen/_data/phrases: file exists
ERROR: Encountered errors while bringing up the project.
```

### CODE REVIEW

**Comment by andykimpe** [comment]
It changes nothing, just by doing the build it works
and moreover it is intended for docker builds to work in this way and not otherwise

the build function to create the image

and the up function to start the image create

on the other hand for the group I didn't even know so much

when looking on google fedora install docker

should land on the page you just gave

and yet have come across this page on which the information is not indicated

https://docs.docker.com/engine/install/fedora/

**Comment by andykimpe** [comment]
your trick of using docker without sudo doesn't even work so you have to update it by indicating sudo on your git

**Comment by FrostyX** [comment]
> the build function to create the image
> and the up function to start the image create

In general, you are right. But `docker-compose up` implicitly does the build if the images don't exist. See
https://docs.docker.com/reference/cli/docker/compose/up/

> docker compose up
> Description
> Builds, (re)creates, starts, and attaches to containers for a service.

So you should be able to go to any project that has `docker-compose.yaml` and simply run `docker-compose up` to get it fully running.

It has been some time since I tried to use `docker-compose` for the Copr project on a fresh system. I will try that and see if we have any bugs there.

> your trick of using docker without sudo doesn't even work so you have to update it by indicating sudo on your git

It works, I've been using it for many years. Is it possible that you forgot on this part?

> You have to log out and log back in (or restart Docker daemon and use newgrp command as mentioned here) for these changes to take effect. Then you can verify if your changes were successful by running Docker without sudo.

**Comment by andykimpe** [comment]
I now know why I got this error

and why sudo was needed

the docker-compose command and now obsolete

it must be replaced by docker compose

so docker-compose up -d

becomes docker compose up -d

I you and updated the code

**Comment by andykimpe** [comment]
on the other hand if you can merge quickly that would suit me because I would like to be able to make personal modifications

off if I make them now you will also have them in this pull

THANKS

**Comment by FrostyX** [comment]
> the docker-compose command and now obsolete
> it must be replaced by docker compose
> so docker-compose up -d
> becomes docker compose up -d

You are right, we will have to do this change eventually but `docker compose` is not yet available in Fedora. On my Fedora 40:

```
[jkadlcik@zeratul ~]$ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
```

If I understand correctly, this pull request
https://src.fedoraproject.org/rpms/docker-compose/pull-request/5
provides the `compose` subcommand, so we have to wait until it is merged and the package is available in Fedora. I am guessing F41+.

So I don't think we want to merge the PR now, but I am glad the development setup works for you now. 


> I would like to be able to make personal modifications
> off if I make them now you will also have them in this pull

Looking forward to them. I recommend taking a look at [git branches](https://www.git-scm.com/docs/git-branch) and more specifically [feature branch workflow](https://docs.gitlab.com/ee/gitlab-basics/feature_branch_workflow.html). It will help you make different changes at the same time and not mix them together in one PR.

**Comment by andykimpe** [comment]
you need to install the docker-compose-plugin package

from the docker-ce repository


```
sudo dnf remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-selinux \
                  docker-engine-selinux \
                  docker-engine \
                  docker-compose
```

```
sudo dnf -y install dnf-plugins-core
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
```


```
 sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
 sudo dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

**Pull request closed without merging**
