### PR TITLE
doc: move the architecture diagram to plantuml

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by praiskup** [comment]
architecture uml

**Comment by praiskup** [comment]
A new one, I've spent "some" time on explaining each of those steps.  The document is now rather big, so I thing it deserves its own doc page (moved).

Screenshot_20230428_173252

**Comment by FrostyX** [comment]
Ok, I think that's detailed enough :laughing: 

Except for the one typo, +1

**Comment by praiskup** [comment]
> Except for the one typo, +1

There will be many :) I will rather re-read all the paragraphs again :-) but if you see something obvious, please tell me!

**Pull request merged**
