### PR TITLE
frontend: show resalloc-webui link in the task queue

### PR DESCRIPTION
**Pull request by FrostyX**
I wasn't sure where to put the link but this seemed like a good idea.

### CODE REVIEW

**Comment by FrostyX** [comment]
Screenshot:

Screenshot_2023-05-15_00-34-33

**Comment by praiskup** [comment]
Thank you for the PR.  Two cons
- the other tabs hold "more interesting info for users"
- other tabs behave like tabs, not sure if external link is expected there
Otherwise LGTM, overall I'm neutral.

**Comment by FrostyX** [comment]
I don't have a strong preference. We can instead have the link in the footer, inside of the statistics page, or somewhere else.

**Comment by FrostyX** [comment]
See also #2718

**Pull request merged**
