### PR TITLE
frontend: unify naming convention for safe methods

### PR DESCRIPTION
**Pull request by nikromen**
Originally, safe methods were considered as methods raising ObjectNotFound for API (mainly with session.one() method). Now methods which returns None or ignores the error completely are also considered as "safe".

For the sake of consistency:
- *_or_none -> returns None if object was not found in the database
- *_safe -> methods that ignores error completely (they basically logs and/or are safe from exceptions)

and renaming some of the current safe methods to normal ones that aren't safe by the new rules

### CODE REVIEW

**Comment by nikromen** [comment]
the fail in CI (copr-common rawhide) seems unrelated to this PR (some problem with package python-six)

also these linter issues were there before :skull:  bad linter! :D

**Comment by praiskup** [comment]
> also these linter issues were there before 💀 bad linter! :D

Detecting that this is a function rename is a rather complicated task not implemented in [csdiff](https://github.com/csutils/csdiff).  You need to be a bit more benevolent if you rename calls. :-)

**Comment by praiskup** [comment]
Can you document the style in `CONTRIBUTE.md`?

**Comment by praiskup** [comment]
Even though, ... I don't know.  I don't feel anyhow "safe" when I'm calling "_safe" methods.  And creating new doesn't make much sense to me.  My personal feeling is that we should much better document the method behavior in docstrings....

**Comment by praiskup** [comment]
I also somewhat dislike that this "safe" concept leaks outside the `frontend/` boundaries :-) :-)

**Comment by nikromen** [comment]
> I also somewhat dislike that this "safe" concept leaks outside the frontend/ boundaries :-) :-)

hmm that's true... but what to do with the safe methods in them? keep them as they are or delete safe suffix?

> Even though, ... I don't know. I don't feel anyhow "safe" when I'm calling "_safe" methods. And creating new doesn't make much sense to me.

As I understood it, they are safe because they catch not-found tracebacks and instead of reraising them (and causing traceback mess in the API calls -> would result to 500 I guess) it translates it to 404 with reasonable message so this is somewhat safe.

>  My personal feeling is that we should much better document the method behavior in docstrings....

I am not against getting rid of the suffixes completely and documenting it... I care only about clarifying the inconsistency :D we can shortly discuss it at standup

**Comment by praiskup** [comment]
> What do you think?

I agree, and to your question - I think we should have `_safe` and `_or_none`.

Repeating my concern;  we should stay on Frontend with this concept, and we should document it.

**Comment by praiskup** [comment]
`_safe` doesn't imply `_or_none` and vice versa, right?  So once could think of a `thing_or_none_safe`?

**Comment by FrostyX** [comment]
> I agree, and to your question - I think we should have _safe and _or_none.

+1

> _safe doesn't imply _or_none and vice versa, right? So once could think of a thing_or_none_safe?

From what I've seen the `_or_none` is used in our code when we query and return things from the database and the `_safe` in sense of "safe from exceptions" is mainly used for doing things and not expecting results. So theoretically there could be `thing_or_none_safe` but I think we won't have any.

> Repeating my concern; we should stay on Frontend with this concept

Looking at the PR changes, even the original code with `_safe` already leaked out frontend

> and we should document it.

Absolutely.
I guess here https://github.com/fedora-copr/copr/blob/main/CONTRIBUTE.md ?

**Comment by praiskup** [comment]
> I guess here https://github.com/fedora-copr/copr/blob/main/CONTRIBUTE.md ?

I'd vote for that one, yes.

**Comment by nikromen** [comment]
no progress

**Comment by nikromen** [comment]
I fixed also a buch of pylint errors with this since the linter was screaming at me with a lot of old errors that were already there so this PR is code-cleanup in general
@praiskup @FrostyX PTAL

**Comment by FrostyX** [comment]
LGTM but I would suggest running beaker tests against this just to be sure.

**Comment by praiskup** [comment]
> LGTM but I would suggest running beaker tests against this just to be sure.

It's going to be done before the release this week, so merging.

**Pull request merged**
