### PR TITLE
Add resalloc-webui container

### PR DESCRIPTION
**Pull request by FrostyX**
Available at http://127.0.0.1:5005/

When running the `resalloc-webui` container for the first time, it will probably be necessary to manually rebuild the `resalloc` container first, to create the database on a shared volume.

    docker-compose up -d --build resalloc

### CODE REVIEW

**Comment by FrostyX** [comment]
I wanted to test https://github.com/praiskup/resalloc/pull/161 and realized we don't have a container for the Resalloc WebUI.

**Comment by FrostyX** [comment]
@pkking not sure if this is interesting for your deployment. The container provides this website:
https://download.copr.fedorainfracloud.org/resalloc

**Comment by pkking** [comment]
> @pkking not sure if this is interesting for your deployment. The container provides this website: https://download.copr.fedorainfracloud.org/resalloc

Hi @FrostyX , our instance deploy with some release behind copr, but this webui looks useful, looking forward for this feature

**Comment by praiskup** [comment]
Thank you!

**Pull request merged**
