### PR TITLE
add persistent storage for resalloc

### PR DESCRIPTION
**Pull request by pkking**
Persist resalloc database and logs on a pv.

Signed-off-by: lichaoran <pkwarcraft@gmail.com>

### CODE REVIEW

**Comment by pkking** [comment]
@TommyLike please help to review :)

**Comment by TommyLike** [comment]
@pkking why we need data volume for resalloc

**Comment by pkking** [comment]
> @pkking why we need data volume for resalloc

For now the log and the single sqlite db stay in the volume.

**Comment by TommyLike** [comment]
> > @pkking why we need data volume for resalloc
> 
> For now the log and the single sqlite db stay in the volume.

Thanks！

**Comment by FrostyX** [comment]
Should I merge @TommyLike, @pkking?

**Comment by TommyLike** [comment]
> Should I merge @TommyLike, @pkking?

Thanks, please merge this.

**Pull request merged**
