### PR TITLE
[WIP]Using args in openshift yaml to avoid tini to be overwritten

### PR DESCRIPTION
**Pull request by pkking**
For #2518 about openshift parts...
In the current docker subdir, i see distgit/keygen/backend using tini, so i change these deployments.
Mark it to WIP and if the changes work, I will remove WIP @praiskup.
The kubernetes subdir need to be some reworks, so i will sync code in another PR(already in progress).

### CODE REVIEW

**Comment by praiskup** [comment]
Hm, I tested with `$ oc exec -c builds -ti copr-backend-1-6c5qc -- bash`:

    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:00 Build dispatcher - processing tasks
     10 pts/0    Ss     0:00 bash
     23 pts/0    R+     0:00 ps 

That said, `tini` doesn't appear to be running?

**Comment by pkking** [comment]
> Hm, I tested with `$ oc exec -c builds -ti copr-backend-1-6c5qc -- bash`:
> 
> ```
> PID TTY      STAT   TIME COMMAND
>   1 ?        Ss     0:00 Build dispatcher - processing tasks
>  10 pts/0    Ss     0:00 bash
>  23 pts/0    R+     0:00 ps 
> ```
> 
> That said, `tini` doesn't appear to be running?

Seems not work as expected, how about `kubectl describe copr-backend-1-6c5qc` and `docker inspect` look like?

**Comment by praiskup** [comment]
https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/applications/deployments
```
You can add a command to a container, which modifies the container’s start-up behavior by overruling the image’s ENTRYPOINT. This is different from a lifecycle hook, which instead can be run once per deployment at a specified time. 
```

Inspecting the pod doesn't show anything interesting (but at least there's no entrypoint field).

So indeed, we must place the `tini` call into the `command:` specification.

**Comment by pkking** [comment]
> https://access.redhat.com/documentation/en-us/openshift_container_platform/4.4/html/applications/deployments
> 
> ```
> You can add a command to a container, which modifies the container’s start-up behavior by overruling the image’s ENTRYPOINT. This is different from a lifecycle hook, which instead can be run once per deployment at a specified time. 
> ```
> 
> Inspecting the pod doesn't show anything interesting (but at least there's no entrypoint field).
> 
> So indeed, we must place the `tini` call into the `command:` specification.

Done, please have a try.

**Comment by praiskup** [comment]
Now it throws `CreateContainerError`:
Error: container create failed: time="2023-03-27T06:26:35Z" level=error msg="runc create failed: unable to start container process: exec: \"/usr/bin/tini\": stat /usr/bin/tini: no such file or directory"

**Comment by pkking** [comment]
> Now it throws `CreateContainerError`: Error: container create failed: time="2023-03-27T06:26:35Z" level=error msg="runc create failed: unable to start container process: exec: "/usr/bin/tini": stat /usr/bin/tini: no such file or directory"

Maybe you should `dnf -y in tini` in dockerfile

**Comment by praiskup** [comment]
It is there: https://github.com/fedora-copr/copr/blob/3de1b08e578ca5b755bdd56a6a4bd777a8a768ff/docker/backend/Dockerfile#L34

**Comment by praiskup** [comment]
Ah, right ... I should upload the updated images.  Testing now!

**Comment by praiskup** [comment]
Thank you!

**Pull request closed without merging**
