### PR TITLE
frontend: include the Amazon Linux logo for Amazon Linux chroots

### PR DESCRIPTION
**Pull request by davdunc**
This is version V08 of the Amazon Linux Image available today. I received this logo from the Project Manager for Amazon Linux directly for the express purpose of including it here in copr. It has been modified to conform to the size constraints and resolution of other images in the frontend.

### CODE REVIEW

**Comment by davdunc** [comment]
See Issue #2666 for additional details related to this PR

**Review by Conan-Kudo — APPROVED** [review]

**Review by Conan-Kudo — CHANGES_REQUESTED** [review]
Can you rename the file `amazonlinux.png`? Then the frontend will automatically pick it up.

**Comment by praiskup** [comment]
Awesome, thank you for the PR!  I second @Conan-Kudo's note, otherwise LGTM.

**Comment by davdunc** [comment]
I'l update it.

**Comment by Conan-Kudo** [comment]
Can you squash all three commits?

**Comment by davdunc** [comment]
yes. squashing the commits.

**Review by praiskup — APPROVED** [review]

**Comment by praiskup** [comment]
Thank you!

**Pull request merged**
