### PR TITLE
frontend: Add backref relationship between Package and Build to silence sqlalchemy warnings

### LINKED ISSUE #2445: copr-frontend alter-chroot warning
During deactivation of chroot I got:
```
Running command: /usr/bin/copr-frontend alter-chroot --action deactivate fedora-35-i386
/usr/lib/python3.11/site-packages/flask_sqlalchemy/__init__.py:550: SAWarning: relationship 'Build.package' will copy column package.id to column build.package_id, which conflicts with relationship(s): 'Package.builds' (copies package.id to build.package_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="builds"' to the 'Build.package' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  mapper = orm.class_mapper(type)
```

### PR DESCRIPTION
**Pull request by nikromen**
Fixes #2445

### CODE REVIEW

**Comment by praiskup** [comment]
Is the testsuite failing because of the change?

**Comment by FrostyX** [comment]
We already have this

```python
class Package(db.Model, helpers.Serializer, CoprSearchRelatedData):
    ...
    builds = db.relationship("Build", order_by="Build.id")
```

which IMHO causes the collision

**Comment by nikromen** [comment]
> which IMHO causes the collision

Yes, thank you. Unluckily... I cannot make alembic work locally on my machine to make migration. Could it somehow be because of the move to F39?

**Comment by nikromen** [comment]
When I run `alembic revision --autogenerate -m "something"` it just generates empty revision

**Review by praiskup — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
