### PR TITLE
rpmbuild: build RPM in one mock call

### LINKED ISSUE #2627: fedora-review is not run
Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=2169218
Opened: 2023-02-12 21:58:55
Opened by: Sandro

---

#### Sandro commented at 2023-02-12 21:58:55:
Description of problem:

I have fedora-review enabled in my Copr repo. However, for a recent build fedora-review was not run for the rawhide and f38 builds.

Version-Release number of selected component (if applicable):

n/a (don't know)

How reproducible:

Always (I tried twice).

Steps to Reproduce:
1. Trigger build in repo with fedora-review enabled

Actual results:

fedora-review dir not present after build

Expected results:

fedora-review dir and results present after build

Additional info:

Example build with missing review: https://copr.fedorainfracloud.org/coprs/gui1ty/reviews/build/5517783/

Build in the same repo (before branching) with unchanged settings and review present: https://copr.fedorainfracloud.org/coprs/gui1ty/reviews/build/4999053/

---

#### Sandro commented at 2023-02-12 22:07:14:
While I was filing this bug I had another build running: https://copr.fedorainfracloud.org/coprs/gui1ty/reviews/build/5519709/

That build took longer than the 'failed' build without review and, surprise, it has the fedora-review results. Not sure why 5517783 wasn't reviewed.

Feel free to close if investigating is too much trouble.

---

#### Jakub Kadlčík commented at 2023-02-15 12:31:11:
Hello Sandro, thank you for the report.
This is the output from the 5517783 build related to the fedora-review

    Running FedoraReview tool
    Running: fedora-review --no-colors --prebuilt --rpm-spec --name cave9 --mock-config /var/lib/copr-rpmbuild/results/configs/child.cfg

    cmd: ['fedora-review', '--no-colors', '--prebuilt', '--rpm-spec', '--name', 'cave9', '--mock-config', '/var/lib/copr-rpmbuild/results/configs/child.cfg']
    cwd: /var/lib/copr-rpmbuild/results
    rc: 2
    stdout: 
    stderr: INFO: Processing local files: cave9
    INFO: Getting .spec and .srpm Urls from : Local files in /var/lib/copr-rpmbuild/results
    ERROR: 'More than one srpm found for: /var/lib/copr-rpmbuild/results/cave9*.src.rpm'

    Fedora review failed
    err:
    INFO: Processing local files: cave9
    INFO: Getting .spec and .srpm Urls from : Local files in /var/lib/copr-rpmbuild/results
    ERROR: 'More than one srpm found for: /var/lib/copr-rpmbuild/results/cave9*.src.rpm'
    The build itself will not be marked as failed because of this
    Running RPMResults tool

---

#### Sandro commented at 2023-02-15 15:08:56:
My bad! I didn't look through the output at all. But I don't understand why it would produce the SRPM twice.

Would that be a bug in copr/mock or a faulty, incorrect spec file?

---

My guess would be a packaging error but I am not sure yet.

There is definitely something going on, you uploaded

    cave9-0.4.1-1.20230207git0.4.1.fc38.src.rpm

And in the results, there are

    cave9-0.4.1-1.20230118git0.4.1.fc38.src.rpm
    cave9-0.4.1-1.20230211git0.4.1.fc38.src.rpm

I would like to try to reproduce this locally, can you please upload
the original SRPM somewhere for me? I tried building from your spec
but I am getting

    $ rpmbuild -bs ~/Downloads/cave9.spec 
    warning: Downloading https://github.com/bart9h/cave9/archive/0.4.1/cave9-0.4.1.tar.gz to /home/jkadlcik/rpmbuild/SOURCES/cave9-0.4.1.tar.gz
    warning: Downloading http://cave9.googlecode.com/files/cave9_data-4.tgz to /home/jkadlcik/rpmbuild/SOURCES/cave9_data-4.tgz
    curl: (22) The requested URL returned error: 404
    error: Couldn't download http://cave9.googlecode.com/files/cave9_data-4.tgz

---

#### Sandro commented at 2023-02-15 22:19:43:
Created attachment 1944431
Original SRPM uploaded to Copr

I believe that's the file I uploaded. Are the uploads not stored in Copr?

---

#### Jakub Kadlčík commented at 2023-02-17 19:06:11:
Thank you

> Are the uploads not stored in Copr?

They are but I wanted to have the same input SRPM as you, not passed through Copr yet

So I am confirming, the issue is 100% reproducible. I tried building it locally and it produced only one SRPM, not two.
I was able to pinpoint the code that produces the two SRPMs. We have `MockBuilder.run` function and it does:

    self.produce_srpm(spec, self.sourcedir, self.resultdir)
    srpm = locate_srpm(self.resultdir)
    self.produce_rpm(srpm, self.resultdir)

The `produce_srpm` creates one SRPM, and then `produce_rpm` creates another SRPM as well as RPMs. Copy-pasting a local reproducer here:

    copr-rpmbuild --chroot fedora-rawhide-x86_64 --task-url  https://copr.fedorainfracloud.org/backend/get-build-task/5537932-fedora-38-x86_64

But I am still not sure whether this is a bug or a packaging issue. I will need to do more digging.

---

#### Jakub Kadlčík commented at 2023-02-17 19:15:24:
Reproducible with just rpmbuild:

    [jkadlcik@zeratul cave9]$ rpm2cpio cave9-0.4.1-1.20230207git0.4.1.fc38.src.rpm | cpio -i
    1756 blocks

    [jkadlcik@zeratul cave9]$ ls *.src.rpm
    cave9-0.4.1-1.20230207git0.4.1.fc38.src.rpm

    [jkadlcik@zeratul cave9]$ rpmbuild -bs cave9.spec --define '_sources .'
    setting SOURCE_DATE_EPOCH=1674000000
    Wrote: /home/jkadlcik/rpmbuild/SRPMS/cave9-0.4.1-1.20230217git0.4.1.fc37.src.rpm

(the NVR changed)

---

#### Sandro commented at 2023-02-18 11:49:51:
(In reply to Jakub Kadlčík from comment #7)
>     [jkadlcik@zeratul cave9]$ rpmbuild -bs cave9.spec --define '_sources .'
>     setting SOURCE_DATE_EPOCH=1674000000
>     Wrote:
> /home/jkadlcik/rpmbuild/SRPMS/cave9-0.4.1-1.20230217git0.4.1.fc37.src.rpm
> 
> (the NVR changed)

Interesting. It's changed to the current date. When I followed your steps locally, except for the --define part not working, it produced cave9-0.4.1-1.20230218git0.4.1.fc37.src.rpm. Does that point to a bug in the %autorelease macro expansion?

---

#### Pavel Raiskup commented at 2023-03-14 09:50:20:
(In reply to Jakub Kadlčík from comment #6)
>     self.produce_srpm(spec, self.sourcedir, self.resultdir)
>     srpm = locate_srpm(self.resultdir)
>     self.produce_rpm(srpm, self.resultdir)

Seems like we shouldn't place the first SRPM into `self.resultdir`.  What we
want to have in the result dir is the results of the final `produce_rpm` Mock
run.  In the normal situation, we override the first source RPM with another
one (with the same name) which is a bad thing.

More "eco" solution would be to start using
https://github.com/rpm-software-management/mock/issues/78

Otherwise, this is IMO a clear  bug in %forgemeta tooling;  no matter the
circumstances, %dist tag shouldn't contain the actual `date` output.  This
makes the build results non-deterministic.

### PR DESCRIPTION
**Pull request by FrostyX**
Fix #2627

### CODE REVIEW

**Comment by praiskup** [comment]
This has been on my TODO list for soooooo long, so it is hard to resist :-)  This e.g. allows us to turn the `root_cache` plugin off (the tarball is generated, but not used).

Do you think it is a good idea _right now_, when we pushed Mock 5.0 forward?  Otherwise LGTM.

**Comment by FrostyX** [comment]
I don't know. If beaker tests are fine with it, I'd say it's probably safe.
But we don't need to rush it if you think it might cause problems.
The issue somehow got into the in-progress column, tagged as a release blocker, so I fixed it :-)

**Comment by praiskup** [comment]
Yeah, I'll try to test tomorrow then.

**Comment by praiskup** [comment]
I only found this bug: https://github.com/rpm-software-management/mock/issues/1179
Though that doesn't seem related to Copr I believe?

**Comment by praiskup** [comment]
> The issue somehow got into the in-progress column, tagged as a release blocker, so I fixed it :-)

Yeah, I did not realize that I'm tagging _that_ issue :-)

**Review by praiskup — APPROVED** [review]
Let's try, thank you!

**Pull request merged**
