### PR TITLE
rpmbuild, dist-git-client: new package dist-git-client

### PR DESCRIPTION
**Pull request by praiskup**
The dist-git-client utility seems generic enough to have it built separately.  This could be useful e.g. for the Konflux build initiative, where we don't necessarily have to build the full copr-rpmbuild package to operate with DistGit.

### CODE REVIEW

**Comment by praiskup** [comment]
Sorry, I thought this will be very easy, and eventually I spend on this like 2 hours :) but seems still worth it.

I'd be curious what you would say if we moved the new package into the [dist-git repository](https://github.com/release-engineering/dist-git).

**Comment by FrostyX** [comment]
> I'd be curious what you would say if we moved the new package into the [dist-git repository](https://github.com/release-engineering/dist-git).

I haven't done a full review yet but that sounds like a good idea to me

**Comment by praiskup** [comment]
> I haven't done a full review yet but that sounds like a good idea to me

Ok, I remove the dist-git-client code in a separate client, and created a PR against the dist-git project: https://github.com/release-engineering/dist-git/pull/63

**Review by FrostyX — APPROVED** [review]

**Comment by praiskup** [comment]
The package review goes here: https://bugzilla.redhat.com/show_bug.cgi?id=2293067

**Comment by praiskup** [comment]
This has +1, dist-git-client is in updates-testing: https://bodhi.fedoraproject.org/updates/?search=dist-git-client

Merging, thank you for the review!

**Pull request merged**
